### ISSUE TITLE
Why SET.py is in binary?

### ISSUE THREAD

**Issue by isaka-james** [U7P4L-IN/TERMUX-SETUP#10]
I don't get your point of putting `SET.py` in binary, because the project is open-source so why are you putting the project binary?

I know that I can use tools to figure out the codes used, 

But my point is why you used binary?, Because the project is supposed to be open source so I could expect plain python codes

Maybe if you could want people to experience performance then you could make another repo of the binary so people who want performance can go there, and the people who want to contribute can contribute to the open source tool here! that's how Linux & Kernel repos are doing.

**Comment by U7P4L-IN** [comment]
I use cpython compiler bcz some people can copy my code without permission. And they also copy my file and upload file in her repo. So i compile my python code for Safety.

And also my all tools are upload for using not for copying.anyone see error then i will try my best to fix and again update tool🙂

Thanks ❤️

**Comment by U7P4L-IN** [comment]
You find lot of temux tools in github.but this time many people compiled her code.So You aslo not get always Main Source Code

And i always get user review and user issue. But i always help every people.i make tools for
Based on human needs.

Welcome❤️.

**Comment by isaka-james** [comment]
Got you but next time you should also leave a space for contributors.. alone projects always they don't go far, there is saying "If you want to go fast then go alone but if you want to go far then go with your friends"
