### ISSUE TITLE
Remove Redirect to GitHub Profile During Tool Installation

### ISSUE THREAD

**Issue by isaka-james** [U7P4L-IN/TERMUX-SETUP#7]
## Issuie:

When installing the tool on Termux, I'm getting redirected to your GitHub profile. Although the installation process completes successfully when I return to Termux, this redirection is frustrating.

## Proposal:

i suggest removing the redirection to the GitHub profile during the installation process. This will improve the user experience and prevent unnecessary frustration.

## Advantages:

1. **Smooth Installation**:
   Removing the redirection ensures a seamless installation process without interruptions.
   
3. **User-Friendly**: 
  Users won't get frustrated by being unexpectedly redirected to the GitHub profile.
   
5. **Enhanced Experience**:
   a smoother installation process contributes to a more positive overall experience for users.

## Considerations:

1. **Purpose of Redirection**:
  Understand the reason behind the redirection and ensure its removal doesn't impact the project's goals.
   
3. **User Feedback**: 
  Gather feedback from other users to confirm if they also find the redirection frustrating.

pleazse considering this suggestion to improve the installation process of the tool.

**Comment by U7P4L-IN** [comment]
ok.i understand
