### ISSUE TITLE
so you're a joke?

### ISSUE THREAD

**Issue by isaka-james** [U7P4L-IN/TERMUX-SETUP#9]
I opened an issue and you marked as complete, i asked about why you deleting my first issue without answering..

so if you don't want want people to contribute it's best for you archive the project or make the project private

**Comment by U7P4L-IN** [comment]
What happened? 

I Already Fix my All issue and update my tools. So i make complete this issue.

**Comment by isaka-james** [comment]
I said you should remove the image folder to make the project light, instead use the github editor to store images
